const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
let pantryCache = [];
const emojiMap = {spinach:"🥬",tomato:"🍅",tomatoes:"🍅",rice:"🍚",yogurt:"🥣",carrot:"🥕",carrots:"🥕",apple:"🍎",banana:"🍌",bread:"🍞",milk:"🥛",potato:"🥔",potatoes:"🥔",onion:"🧅",egg:"🥚",eggs:"🥚",cheese:"🧀",lemon:"🍋",beans:"🫘",lettuce:"🥗"};
function emojiFor(name){const n=name.toLowerCase();for(const k in emojiMap)if(n.includes(k))return emojiMap[k];return "🥫"}
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2600)}
function goTo(id){$$(".page").forEach(p=>p.classList.toggle("active-page",p.id===id));$$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.target===id));window.scrollTo({top:0,behavior:"smooth"});if(id==="pantry")loadPantry();if(id==="impact")loadStats()}
$$(".nav").forEach(b=>b.addEventListener("click",()=>goTo(b.dataset.target)));
$$("[data-goto]").forEach(b=>b.addEventListener("click",()=>goTo(b.dataset.goto)));
async function loadStats(){const r=await fetch("/api/stats"),s=await r.json();$("#pantryCount").textContent=s.pantry_count;$("#urgentCount").textContent=s.urgent_count;$("#savedCount").textContent=s.saved_count;$("#savedValue").textContent=money(s.saved_value);$("#impactCount").textContent=s.saved_count;$("#impactValue").textContent=money(s.saved_value)}
async function loadPantry(){const r=await fetch("/api/pantry");pantryCache=await r.json();renderPantry();renderPriority();loadStats()}
function renderPriority(){const items=pantryCache.filter(x=>x.days_left<=2).slice(0,4);const el=$("#priorityList");if(!items.length){el.innerHTML='<div class="empty-state"><b>Nothing urgent right now ✨</b><p>Your pantry is looking good.</p></div>';return}el.innerHTML=items.map(x=>`<div class="food-row"><div class="food-emoji">${emojiFor(x.name)}</div><div class="food-info"><b>${esc(x.name)}</b><small>${esc(x.quantity)} · ${x.days_left<0?"Date passed":x.days_left===0?"Date is today":x.days_left+" day(s) left"}</small></div><span class="due">${x.days_left<0?"Check":x.days_left===0?"Today":"Soon"}</span></div>`).join("")}
function renderPantry(){const query=($("#pantrySearch")?.value||"").toLowerCase();const items=pantryCache.filter(x=>x.name.toLowerCase().includes(query));$("#pantryTotal").textContent=items.length+" items";const grid=$("#pantryGrid");if(!items.length){grid.innerHTML='<div class="panel">No matching food found. Add an ingredient to get started.</div>';return}grid.innerHTML=items.map(x=>`<article class="pantry-card"><div class="pantry-card-top"><span class="pantry-emoji">${emojiFor(x.name)}</span><button class="delete-btn" title="Remove item" onclick="removeItem(${x.id})">✕</button></div><h3>${esc(x.name)}</h3><p>${esc(x.quantity)} · ${esc(x.category)}</p><div class="pantry-card-bottom"><small>${x.days_left<0?"Date passed — check safety":x.days_left===0?"Date is today":x.days_left+" day(s) until date"}</small><button class="save-btn" onclick="saveItem(${x.id})">✓ I used it</button></div></article>`).join("")}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("#pantrySearch").addEventListener("input",renderPantry);
$("#showAdd").addEventListener("click",()=>{$("#addPanel").classList.toggle("hidden");$("#addPanel").scrollIntoView({behavior:"smooth",block:"nearest"})});
$("#addForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);const payload=Object.fromEntries(f.entries());const r=await fetch("/api/pantry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok){$("#formMessage").textContent=data.error||"Could not add item.";return}e.target.reset();$("#formMessage").textContent="Added to your pantry.";await loadPantry();toast("Ingredient added!");});
async function removeItem(id){await fetch("/api/pantry/"+id,{method:"DELETE"});await loadPantry();toast("Removed from pantry")}
async function saveItem(id){const item=pantryCache.find(x=>x.id===id);if(!item)return;const value=prompt("Estimated value of this food you used instead of discarding (₹):","30");if(value===null)return;const cost=Number(value);if(!Number.isFinite(cost)||cost<0){toast("Enter a valid non-negative amount.");return}await fetch("/api/saved",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:item.name,cost})});await fetch("/api/pantry/"+id,{method:"DELETE"});await loadPantry();toast("Nice! Food rescued and impact logged.");}
$("#generateRecipes").addEventListener("click",async()=>{const btn=$("#generateRecipes");btn.disabled=true;btn.textContent="✦ Creating your recipes…";$("#recipeOutput").classList.remove("empty-state");$("#recipeOutput").textContent="Checking your pantry and preparing ideas…";try{const r=await fetch("/api/recipes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preferences:$("#preferences").value})});const data=await r.json();$("#recipeMode").textContent=data.mode;$("#recipeOutput").textContent=data.recipes_text;$("#recipeOutput").style.whiteSpace="pre-wrap"}catch(e){$("#recipeOutput").textContent="Couldn't generate ideas. Please try again."}finally{btn.disabled=false;btn.innerHTML='✦ Generate recipes <span>→</span>'}});
async function loadImpactLog(){/* Demo history is summarized by the API; local display is intentionally transparent. */const el=$("#impactLog");el.innerHTML='<div class="log-row"><span><b>Impact log</b><br><small>Items you mark as used appear in your totals.</small></span><span>Live totals ↗</span></div>'}
const originalLoadStats=loadStats;loadStats=async function(){await originalLoadStats();await loadImpactLog()};
loadPantry();
